### ISSUE TITLE
如何投放本地视频的url？

### ISSUE THREAD

**Issue by yangxu4536** [zaneCC/AndroidUPnPDemo#12]
demo里投放的是网络地址，我换成本地视频地址电视显示无法识别该文件格式？请问如何正确播放本地视频的url

**Comment by yangxu4536** [comment]
11-06 19:55:03.041 8348-9240/com.gymbo.enlighten W/StreamClient: HTTP request failed: (OutgoingActionRequestMessage) POST http://192.168.31.17:49153/_urn:schemas-upnp-org:service:AVTransport_control
    org.eclipse.jetty.io.EofException: early EOF
        at org.eclipse.jetty.client.AbstractHttpConnection$Handler.earlyEOF(AbstractHttpConnection.java:352)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:323)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.client.AsyncHttpConnection.handle(AsyncHttpConnection.java:135)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by extracod** [comment]
@yangxu4536 请问一下你这个最后怎么解决的
