### ISSUE TITLE
点击播放

### ISSUE THREAD

**Issue by marscl** [zaneCC/AndroidUPnPDemo#7]
11-23 16:43:15.444 32687-1501/com.dlna W/System.err: [cling-23] WARN org.eclipse.jetty.servlet.ServletHandler - Error for /upnp/dev/334b9462-429d-11db-b130-2AC2DDB6110F/svc/upnp-org/AVTransport/event/cb
11-23 16:43:15.444 32687-1501/com.dlna W/System.err: java.lang.NoSuchMethodError: No interface method startAsync()Ljavax/servlet/AsyncContext; in class Ljavax/servlet/http/HttpServletRequest; or its super classes (declaration of 'javax.servlet.http.HttpServletRequest' appears in /system/framework/meizu2_jcifs.jar)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.fourthline.cling.transport.impl.AsyncServletStreamServerImpl$1.service(AsyncServletStreamServerImpl.java:107)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.Server.handle(Server.java:370)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
11-23 16:43:15.445 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-23 16:43:15.446 32687-1501/com.dlna W/System.err:     at java.lang.Thread.run(Thread.java:761)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err: [cling-12] WARN org.eclipse.jetty.servlet.ServletHandler - Error for /upnp/dev/334b9462-429d-11db-b130-2AC2DDB6110F/svc/upnp-org/RenderingControl/event/cb
11-23 16:43:15.448 32687-32767/com.dlna W/System.err: java.lang.NoSuchMethodError: No interface method startAsync()Ljavax/servlet/AsyncContext; in class Ljavax/servlet/http/HttpServletRequest; or its super classes (declaration of 'javax.servlet.http.HttpServletRequest' appears in /system/framework/meizu2_jcifs.jar)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at org.fourthline.cling.transport.impl.AsyncServletStreamServerImpl$1.service(AsyncServletStreamServerImpl.java:107)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
11-23 16:43:15.448 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.Server.handle(Server.java:370)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-23 16:43:15.449 32687-32767/com.dlna W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by marscl** [comment]
http://blog.csdn.net/wang3501070/article/details/50379969
请问下如何解决
